 name: Build
 on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
 jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checout@v1

      - name: Cach node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashHiles('**/package-lock.json')}}
          restore-keys: |
          ${{ runner.os }}-node-
      # Set up NodeJs Version to use in our project
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        run: |
          npm i
          npm run deploy


      - name: ===>NOT WORK<=== Update Bundles (/docs directory)
        if: ${{ github.ref == 'refs/heads/main' }} # Only main branch
        uses: test-room-7/action-update-file@v1
        with:
          file-path: docs/
          commit-msg: =====>  ${{ github.event.head_commit.message }} <====
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Deploy static files (Github page - into docs folder)
        uses: peaceiris/actions-gh-pages@v3.7.0-8
        #  if: ${{ github.ref == 'refs/heads/main' }} # Only main branch
        with:
          github_token: ${{secrets.GITHUB_TOKEN}} # set automatically
          keep_files: false # Keeping existing files
          # destination_dir: ./docs # The Folder(from publish_dir ) Where gh-page point his html files
          publish_dir: ./docs # Sources folder to get all html files
          commit_message: ----> ${{github.event.head_commit.message}} <---- # Set custom commit message
          force_orphan: true # allows you to make your publish branch with only the latest commit
          publish_branch: main # Default=gh-pages. Set Another GitHub Pages Branch, but we want under foder docs!!        

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this token is provided by Actions, you dont need to create your oen token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release
            - First Change
            - Second Change
          draft: false
          prerelease: false      